name: Publish tag assets

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  publish-tag-assets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Upload release artifacts to Github release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./client/dist/chatfall.*
            ./server/dist-bin/chatfall-*
            ./server/dist/chatfall-server.*

      - name: Publish client NPM package
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"
          bun run publish-npm
