name: Publish Github release

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write
  pull-requests: write

jobs:
  publish-github-release:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Create GitHub Release
        uses: googleapis/release-please-action@v4
        id: release
        with:
          skip-github-pull-request: true
          config-file: release-please-config.json
          manifest-file: release-please-manifest.json
          repo-url: hiddentao/chatfall
